### PR TITLE
Add CLA github action

### LINKED ISSUE #84: Add CLA to repository
As we value 3rd party contributions (and more have been coming in), please coordinate to add the cla assistent to all of our repos. You can find an example in the safe-react repo: https://github.com/gnosis/safe-react/blob/development/.github/workflows/cla.yml Also make sure not to merge contributions of external devs before this is in place please

### PR DESCRIPTION
**Pull request by mikheevm**
This PR:
- Adds CLA GitHub action and closes #84

### CODE REVIEW

**Review by germartinez — APPROVED** [review]
There is also this legal text to add
https://github.com/gnosis/contract-proxy-kit/blob/master/GNOSISCLA.md

**Comment by mikheevm** [comment]
@germartinez 
```
          path-to-cla-document: 'https://github.com/gnosis/safe-react/blob/master/GNOSISCLA.md'
```

I just linked the one we have in safe-react. I guess the CLA is the same for every repo across gnosis

**Comment by rmeissner** [comment]
We should copy it over actually, and not link the other repo.

**Comment by mikheevm** [comment]
Putting this on hold as I asked the legal team whether it's acceptable to use a shared document

**Pull request merged**
