### PR TITLE
Avoid setting state for unmounted component

### PR DESCRIPTION
**Pull request by everdimension**

### CODE REVIEW

**Comment by mikheevm** [comment]
@everdimension Thank you for the contribution! Could you please sign the CLA? Then we'll be able to merge it.

**Comment by everdimension** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by everdimension** [comment]
recheckcla

**Comment by mikheevm** [comment]
oops, there are a lot of conflicts, I'll just recreate the PR myself checking out from development. Thank you for the contribution!

**Pull request closed without merging**
