### PR TITLE
v0.4.0

### PR DESCRIPTION
**Pull request by germartinez**
This Release:
- Add RequestID to every message between the interface and an app. Now you can map the request and response. (https://github.com/gnosis/safe-apps-sdk/issues/17)
- Add new events for transaction confirmation  and rejection (https://github.com/gnosis/safe-apps-sdk/issues/37 https://github.com/gnosis/safe-apps-sdk/issues/17)
- Add a way to query transaction by safeTxHash (https://github.com/gnosis/safe-apps-sdk/issues/29)
- Type enhancements https://github.com/gnosis/safe-apps-sdk/pull/46

### CODE REVIEW

**Comment by mikheevm** [comment]
@germartinez is this a dependency for you or we can wait when Richard plays with the dev version on his ecosystem friday?

**Comment by germartinez** [comment]
> @germartinez is this a dependency for you or we can wait till Richard plays with the dev version on his ecosystem friday?

We can wait ;)

**Review by nicosampler — APPROVED** [review]

**Comment by mikheevm** [comment]
I'll add a description tomorrow and release it

**Comment by nicosampler** [comment]
> I'll add a description tomorrow and release it

@mikheevm, something I can help with to release it?

**Comment by mikheevm** [comment]
@nicosampler no, thank you! I'll release it now

**Pull request merged**
